# Generated by Django 5.0.2 on 2024-03-05 05:17

import backend_app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateName', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('currentEmployer', models.CharField(max_length=255)),
                ('totalExperience', models.CharField(max_length=255)),
                ('ctc', models.CharField(max_length=255)),
                ('ectc', models.CharField(max_length=255)),
                ('noticePeriod', models.CharField(max_length=255)),
                ('relocate', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('remarks', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('interview', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Recruiter', 'Recruiter'), ('Manager', 'Manager'), ('Business Development Partner', 'Business Development Partner'), ('Business Development Partner Manager', 'Business Development Partner Manager'), ('Account Manager', 'Account Manager')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='graduationYear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), backend_app.models.current_year_validator]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='emailID',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='emergencyContactNumber',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phoneNumber',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityName', models.CharField(max_length=255)),
                ('organizationStatus', models.CharField(max_length=255)),
                ('estYear', models.CharField(max_length=4)),
                ('proprieterName', models.CharField(max_length=255)),
                ('officeAddress', models.TextField()),
                ('branchAddress', models.TextField()),
                ('companyPerson', models.CharField(max_length=255)),
                ('companyDesignation', models.CharField(max_length=255)),
                ('companyNumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)])),
                ('companyFax', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)])),
                ('companyEmail', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('industryNature', models.CharField(max_length=255)),
                ('companyCIN', models.CharField(max_length=255)),
                ('companyPAN', models.CharField(max_length=10)),
                ('companyGST', models.CharField(max_length=15)),
                ('accountManager', models.CharField(max_length=255)),
                ('billingCity', models.CharField(max_length=255)),
                ('billingCountry', models.CharField(max_length=255)),
                ('bdpName', models.ForeignKey(limit_choices_to={'role__role': 'Business Development Partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='bdp_clientregistrations', to='backend_app.userdata')),
                ('bdpmName', models.ForeignKey(limit_choices_to={'role__role': 'Business Development Partner Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='bdpm_clientregistrations', to='backend_app.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleDesignation', models.CharField(max_length=255)),
                ('clientName', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('closureDate', models.DateField()),
                ('jobType', models.CharField(max_length=255)),
                ('jobStatus', models.CharField(max_length=255)),
                ('workExperience', models.CharField(max_length=255)),
                ('industryNature', models.CharField(max_length=255)),
                ('compensation', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('eligibilityCriteria', models.TextField()),
                ('primaryResponsibilities', models.TextField()),
                ('mandatorySkills', models.TextField()),
                ('desirableSkills', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('accountManager', models.ForeignKey(limit_choices_to={'role__role': 'Account Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions_as_account_manager', to='backend_app.userdata')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_job_descriptions', to='backend_app.userdata')),
                ('assignedRecruiters', models.ForeignKey(limit_choices_to={'role__role': 'Recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_job_descriptions', to='backend_app.userdata')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.clientregistration')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='job_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.jobdescription'),
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_app.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='PendingClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('client_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_app.clientregistration')),
            ],
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.pendingclientregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_app.clientregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.userdata')),
                ('rejection_reason', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.rejectionreason')),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.role'),
        ),
    ]
