# Generated by Django 5.0.2 on 2024-03-11 09:32

import s3direct.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_assessment_role_alter_education_graduationyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='resume',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
