# Generated by Django 5.0.2 on 2024-03-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_jobdescription_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregistration',
            name='bdpName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='bdpmName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='branchAddress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='companyNumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='officeAddress',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
