# Generated by Django 5.0.2 on 2024-03-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_alter_clientregistration_bdpname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregistration',
            name='companyNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
