# Generated by Django 5.0.2 on 2024-03-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_alter_clientregistration_companynumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregistration',
            name='companyNumber',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
