# Generated by Django 5.0.2 on 2024-03-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_userdata_esino_userdata_pfuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='fullName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
